### ISSUE TITLE
#Question Required APT Packages?

### ISSUE THREAD

**Issue by matt-laird** [Prevole/rpihc#1]
Hey this is a cool restructure of the original "example" by Waveshare, nice work. 
I'm interested to know what APT packages you used to get this running, what are is dependencies? 
I only ask because I've followed the official Waveshare documentation and it leads something to be desired, wondering if you have a better list of dependencies.

**Comment by Prevole** [comment]
Yes, I have two medium articles in preparation regarding my Waveshare devices.

For the 2.4 inch module:

```bash
# ① Update the apt get definitions
root@ubuntu:# apt-get update

# ② Install pip3 and RPi.GPIO
root@ubuntu:# apt-get install python3-pip RPi.GPIO

# ③ Install python modules
root@ubuntu:# pip3 install smbus pillow numpy spidev
```

For the OLED display, the procedure is the same. We just do not need the spidev dependency.

```bash
# ① Update the apt get definitions
root@ubuntu:# apt-get update

# ② Install pip3 and RPi.GPIO
root@ubuntu:# apt-get install python3-pip RPi.GPIO

# ③ Install python modules
root@ubuntu:# pip3 install smbus pillow numpy
```

In the end, I did need all the things that are present in the Waveshare documentation. In the end, for Python setup, not all the things described in the Waveshare documentation are required.
